### ISSUE TITLE
连不上自己的服务器

### ISSUE THREAD

**Issue by Kevinwu901113** [Turing-Project/AntiFraudChatBot#9]
用的华为云服务器，服务器已经运行wechaty
然后自己本机运行dialog.py时遇到
wechaty_puppet.exceptions.WechatyPuppetConfigurationError: WechatyPuppetConfigurationError("can't not ping endpoint: 我服务器的虚拟ip和端口8788", None, None)
当我注释掉代码中的
os.environ['WECHATY_PUPPET_SERVICE_ENDPOINT']
报错里面的虚拟ip会变成我服务器的ip
token检查是没问题的，服务器有jsonrpc
VERB Io on(jsonrpc) send({"id":-9007199254689482,"jsonrpc":"2.0","result":8788})
要怎么解决？

**Comment by Kevinwu901113** [comment]
已解决

**Comment by 980202006** [comment]
@Kevinwu901113 请问，大佬怎么解决的？

**Comment by Kevinwu901113** [comment]
> @Kevinwu901113 请问，大佬怎么解决的？

额我不是大佬，到今天这个都还跑不起来，服务器的话是安全组策略里面我是tcp和udp的这个端口全放开

**Comment by 980202006** [comment]
好的谢谢

**Comment by 980202006** [comment]
![image](https://user-images.githubusercontent.com/24452502/208071966-a0b1c202-7c73-40f6-89a6-8f489f526fb1.png)
@Kevinwu901113 tcp和udp的这个端口全放开是这样的吗
